### ISSUE TITLE
Add discord admin actions

### ISSUE THREAD

**Issue by schana** [schana/carim-discord-bot#10]
Add a few standard administration actions to the bot, such as auto roles, welcome messages, etc.

This might not be necessary, as there are already numerous other implementations/active bots that can perform this functionality. It might be worth looking into a plugin-structured Carim bot package.

**Comment by Costageo** [comment]
If there is at some point going to be a plug-in package for the bot, it may be worth implementing each plug-in bit by bit. Also adding the ability to turn on and turn off each plug-in to suit the users needs

**Comment by schana** [comment]
I'm going to close this as there are many other bots out there that already have this functionality, such as https://aprilbot.me/
